---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-asa-code-check-pr
spec:
  pipelineSpec:
     params:
       - name: repo_url
       - name: revision
     workspaces:
     - name: source
     tasks:
       - name: fetch
         taskRef:
           name: git-clone
         params:
           - name: url
             value: $(params.repo_url)
           - name: revision
             value: $(params.revision)
         workspaces:
           - name: output
             workspace: source
       - name: pthon-lint
         runAfter: [fetch]
         taskRef:
           name: pylint
         params:
           - name: path
             value: "tekton_neat/"
           - name: args
             value: ["-r", "y"]
         workspaces:
           - name: source
             workspace: source
       - name: python-unittest
         runAfter: [fetch]
         taskRef:
           name: pytest
         params:
           - name: ARGS
             value: "--cov=./ --cov-report=xml"
           - name: REQUIREMENTS_FILE
             value: "requirements_dev.txt"
         workspaces:
           - name: source
             workspace: source
       - name: codecov
         runAfter: [python-unittest]
         taskRef:
           name: codecov
         params:
           - name: codecov-token-secret
             value: "chmouel-tektonneat-codecov"
           - name: codecov-token-secret-key
             value: "token"
         workspaces:
           - name: source
             workspace: source

  params:
    - name: repo_url
      value: {{repo_url}}
    - name: revision
      value: {{revision}}
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
